### PR TITLE
Moved private key to .env file and added a configurable delay

### PR DESCRIPTION
**Pull request by nbstrong**

### CODE REVIEW

**Comment by rhiroshi** [comment]
Hi! This method would limit the ammount of wallets we could run with

**Comment by nbstrong** [comment]
How?

**Comment by rhiroshi** [comment]
Supose we want a third wallet, we would need to add a variable on .env and add it on the hardhat config too.
Possibile solution on [stackoverflow](https://stackoverflow.com/questions/31552125/defining-an-array-as-an-environment-variable-in-node-js)

**Comment by nbstrong** [comment]
That works. I'll submit a fix later.

**Comment by rhiroshi** [comment]
yes i was planning to change it too after i finished the wallet iteration feature. I'll wait your changes to merge it then!

**Comment by nbstrong** [comment]
Done

**Pull request merged**
